### ISSUE TITLE
Not able to upload images to aws ecr.

### ISSUE THREAD

**Issue by sumitrathore42** [eclass/semantic-release-docker#400]
2021-07-14T11:04:13.562Z semantic-release:plugins options for @eclass/semantic-release-docker/prepare: { baseImageName: 'image_name',
  registries:
   [ { url: 'xxxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com',
       imageName: 'xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/image_name',
       user: 'AWS_DOCKER_USER',
       password: 'AWS_DOCKER_PASSWORD' } ] }
[11:04:25 AM] [semantic-release] ��� ���  EDOCKERLOGIN Error login to docker registry.
Try login to docker registry.
{ AggregateError: 
    SemanticReleaseError: Error login to docker registry.
        at module.exports (/node_modules/@eclass/semantic-release-docker/src/get-error.js:14:10)
        at module.exports (/node_modules/@eclass/semantic-release-docker/src/verify.js:38:23)
    at /usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at process._tickCallback (internal/process/next_tick.js:68:7) name: [32m'AggregateError'[39m }

**Comment by lgaticaq** [comment]
Hi. Check this example `gitlab-ci.yml`:
```yml
semantic-release:
  image: node:alpine
  services:
    - docker:dind
  variables:
    AWS_DOCKER_USER: AWS
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - apk add --no-cache docker py3-pip python2
    - pip3 install awscli
    - export AWS_DOCKER_PASSWORD=$(aws ecr get-authorization-token --region $AWS_REGION --output text --query 'authorizationData[].authorizationToken' | base64 -d | cut -d: -f2)
  script:
    - npx semantic-release
  only:
    - master
```
